-- MySQL Script generated by MySQL Workbench
-- Tue Feb 27 14:41:11 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema poytavaraus
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `poytavaraus` ;

-- -----------------------------------------------------
-- Schema poytavaraus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `poytavaraus` DEFAULT CHARACTER SET latin1 ;
USE `poytavaraus` ;

-- -----------------------------------------------------
-- Table `poytavaraus`.`ilmoitus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poytavaraus`.`ilmoitus` ;

CREATE TABLE IF NOT EXISTS `poytavaraus`.`ilmoitus` (
  `ilmoitus_id` INT(11) NOT NULL AUTO_INCREMENT,
  `viesti` VARCHAR(225) NOT NULL,
  `vastaanottaja` VARCHAR(225) NOT NULL,
  PRIMARY KEY (`ilmoitus_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `poytavaraus`.`pöytä`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poytavaraus`.`pöytä` ;

CREATE TABLE IF NOT EXISTS `poytavaraus`.`pöytä` (
  `pöytä_id` INT(11) NOT NULL AUTO_INCREMENT,
  `kapasiteetti` INT(11) NOT NULL,
  `lisätiedot` VARCHAR(225) NULL DEFAULT NULL,
  `on_varattu` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`pöytä_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `poytavaraus`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poytavaraus`.`users` ;

CREATE TABLE IF NOT EXISTS `poytavaraus`.`users` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `etunimi` VARCHAR(255) NOT NULL,
  `sukunimi` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `poytavaraus`.`varaus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poytavaraus`.`varaus` ;

CREATE TABLE IF NOT EXISTS `poytavaraus`.`varaus` (
  `varaus_id` INT(11) NOT NULL AUTO_INCREMENT,
  `päivämäärä` DATE NOT NULL,
  `aika` TIME NOT NULL,
  `henkilömäärä` INT(11) NOT NULL,
  `vahvistuskoodi` VARCHAR(45) NULL DEFAULT NULL,
  `erikoispyynnöt` VARCHAR(225) NULL DEFAULT NULL,
  `user_id` INT(11) NOT NULL,
  `ilmoitus_id` INT(11) NULL,
  `pöytä_id` INT(11) NOT NULL,
  PRIMARY KEY (`varaus_id`, `user_id`, `pöytä_id`),
  INDEX `fk_varaus_users1_idx` (`user_id` ASC, `ilmoitus_id` ASC) VISIBLE,
  INDEX `fk_varaus_pöytä1_idx` (`pöytä_id` ASC) VISIBLE,
  CONSTRAINT `fk_varaus_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `poytavaraus`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_varaus_pöytä1`
    FOREIGN KEY (`pöytä_id`)
    REFERENCES `poytavaraus`.`pöytä` (`pöytä_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -----------------------------------------------------
-- Data for table `poytavaraus`.`pöytä`
-- -----------------------------------------------------
START TRANSACTION;
USE `poytavaraus`;
INSERT INTO `poytavaraus`.`pöytä` (`pöytä_id`, `kapasiteetti`, `lisätiedot`, `on_varattu`) VALUES (DEFAULT, 4, 'ikkunan vieressä', NULL);
INSERT INTO `poytavaraus`.`pöytä` (`pöytä_id`, `kapasiteetti`, `lisätiedot`, `on_varattu`) VALUES (DEFAULT, 4, '-', NULL);
INSERT INTO `poytavaraus`.`pöytä` (`pöytä_id`, `kapasiteetti`, `lisätiedot`, `on_varattu`) VALUES (DEFAULT, 10, 'kabinetti', NULL);
INSERT INTO `poytavaraus`.`pöytä` (`pöytä_id`, `kapasiteetti`, `lisätiedot`, `on_varattu`) VALUES (DEFAULT, 2, 'käytävä', NULL);
INSERT INTO `poytavaraus`.`pöytä` (`pöytä_id`, `kapasiteetti`, `lisätiedot`, `on_varattu`) VALUES (DEFAULT, 6, 'loosi', NULL);
INSERT INTO `poytavaraus`.`pöytä` (`pöytä_id`, `kapasiteetti`, `lisätiedot`, `on_varattu`) VALUES (DEFAULT, 6, 'loosi ikkunan vierestä', NULL);
INSERT INTO `poytavaraus`.`pöytä` (`pöytä_id`, `kapasiteetti`, `lisätiedot`, `on_varattu`) VALUES (DEFAULT, 4, '\"baaritiski\"', NULL);

COMMIT;


