-- MySQL Script generated by MySQL Workbench
-- Mon Mar 25 11:32:21 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema poytavaraus
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `poytavaraus` ;

-- -----------------------------------------------------
-- Schema poytavaraus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `poytavaraus` DEFAULT CHARACTER SET latin1 ;
USE `poytavaraus` ;

-- -----------------------------------------------------
-- Table `poytavaraus`.`pöytä`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poytavaraus`.`pöytä` ;

CREATE TABLE IF NOT EXISTS `poytavaraus`.`pöytä` (
  `pöytä_id` INT(11) NOT NULL AUTO_INCREMENT,
  `kapasiteetti` INT(11) NOT NULL,
  `lisätiedot` VARCHAR(225) NULL DEFAULT NULL,
  PRIMARY KEY (`pöytä_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `poytavaraus`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poytavaraus`.`users` ;

CREATE TABLE IF NOT EXISTS `poytavaraus`.`users` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `etunimi` VARCHAR(255) NOT NULL,
  `sukunimi` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `poytavaraus`.`varaus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poytavaraus`.`varaus` ;

CREATE TABLE IF NOT EXISTS `poytavaraus`.`varaus` (
  `varaus_id` INT(11) NOT NULL AUTO_INCREMENT,
  `päivämäärä` DATE NOT NULL,
  `aika` TIME NOT NULL,
  `henkilömäärä` INT(11) NOT NULL,
  `erikoispyynnöt` VARCHAR(225) NULL DEFAULT NULL,
  `user_id` INT(11) NOT NULL,
  `pöytä_id` INT(11) NOT NULL,
  `loppumisaika` TIME NULL,
  `lisätiedot` VARCHAR(225) NULL,
  `tilaisuus` VARCHAR(45) NULL,
  `on_vahvistettu` TINYINT NOT NULL DEFAULT 0,
  `iso_poyta` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`varaus_id`, `user_id`, `pöytä_id`),
  INDEX `fk_varaus_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_varaus_pöytä1_idx` (`pöytä_id` ASC) VISIBLE,
  CONSTRAINT `fk_varaus_pöytä1`
    FOREIGN KEY (`pöytä_id`)
    REFERENCES `poytavaraus`.`pöytä` (`pöytä_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_varaus_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `poytavaraus`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `poytavaraus`.`aukiolo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poytavaraus`.`aukiolo` ;

CREATE TABLE IF NOT EXISTS `poytavaraus`.`aukiolo` (
  `avausaika` TIME NULL,
  `sulkuaika` TIME NULL,
  PRIMARY KEY (`avausaika`, `sulkuaika`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `poytavaraus`.`pöytä`
-- -----------------------------------------------------
START TRANSACTION;
USE `poytavaraus`;
INSERT INTO `poytavaraus`.`pöytä` (`pöytä_id`, `kapasiteetti`, `lisätiedot`) VALUES (1, 4, 'Loosi');
INSERT INTO `poytavaraus`.`pöytä` (`pöytä_id`, `kapasiteetti`, `lisätiedot`) VALUES (2, 6, 'Loosi');
INSERT INTO `poytavaraus`.`pöytä` (`pöytä_id`, `kapasiteetti`, `lisätiedot`) VALUES (3, 2, NULL);
INSERT INTO `poytavaraus`.`pöytä` (`pöytä_id`, `kapasiteetti`, `lisätiedot`) VALUES (4, 10, 'Kabinetti');
INSERT INTO `poytavaraus`.`pöytä` (`pöytä_id`, `kapasiteetti`, `lisätiedot`) VALUES (5, 12, 'Kabinetti');
INSERT INTO `poytavaraus`.`pöytä` (`pöytä_id`, `kapasiteetti`, `lisätiedot`) VALUES (6, 4, 'Baaritiski');
INSERT INTO `poytavaraus`.`pöytä` (`pöytä_id`, `kapasiteetti`, `lisätiedot`) VALUES (7, 4, 'Käytävä');
INSERT INTO `poytavaraus`.`pöytä` (`pöytä_id`, `kapasiteetti`, `lisätiedot`) VALUES (8, 2, 'Keittiön vierus');
INSERT INTO `poytavaraus`.`pöytä` (`pöytä_id`, `kapasiteetti`, `lisätiedot`) VALUES (9, 4, 'Ikkunapaikka');
INSERT INTO aukiolo (avausaika, sulkuaika) VALUES ('10:00:00', '21:00:00');

COMMIT;

